version: "3.7"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: shuup
      POSTGRES_USER: shuup
      POSTGRES_PASSWORD: shuup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  shuup:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.sqlite
      - /app/shuup/admin/static
      - /app/shuup/front/static
      - /app/shuup/gdpr/static
      - /app/shuup/notify/static
      - /app/shuup/regions/static
      - /app/shuup/themes/classic_gray/static
      - /app/shuup/xtheme/static
      - /app/shuup.egg-info
    tty: true
    restart: unless-stopped

  

volumes:
  postgres_data:
